// Code generated by "stringer -type=SyncStatus,ConflictResolutionStatus -output=types_string.go"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Active-0]
	_ = x[Idle-1]
	_ = x[Scheduled-2]
	_ = x[Paused-3]
	_ = x[Disabled-4]
}

const _SyncStatus_name = "ActiveIdleScheduledPausedDisabled"

var _SyncStatus_index = [...]uint8{0, 6, 10, 19, 25, 33}

func (i SyncStatus) String() string {
	if i < 0 || i >= SyncStatus(len(_SyncStatus_index)-1) {
		return "SyncStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SyncStatus_name[_SyncStatus_index[i]:_SyncStatus_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unresolved-0]
	_ = x[ResolvedSource-1]
	_ = x[ResolvedTarget-2]
	_ = x[Merged-3]
}

const _ConflictResolutionStatus_name = "UnresolvedResolvedSourceResolvedTargetMerged"

var _ConflictResolutionStatus_index = [...]uint8{0, 10, 24, 38, 44}

func (i ConflictResolutionStatus) String() string {
	if i < 0 || i >= ConflictResolutionStatus(len(_ConflictResolutionStatus_index)-1) {
		return "ConflictResolutionStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConflictResolutionStatus_name[_ConflictResolutionStatus_index[i]:_ConflictResolutionStatus_index[i+1]]
}
