// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"

	"github.com/vinitparekh17/syncsnipe/internal/types"
)

type Conflict struct {
	ID               int64                          `json:"id"`
	SourcePath       string                         `json:"sourcePath"`
	TargetPath       string                         `json:"targetPath"`
	SourceHash       string                         `json:"sourceHash"`
	TargetHash       string                         `json:"targetHash"`
	SourceTime       int64                          `json:"sourceTime"`
	TargetTime       int64                          `json:"targetTime"`
	DetectedAt       int64                          `json:"detectedAt"`
	ResolutionStatus types.ConflictResolutionStatus `json:"resolutionStatus"`
	ResolvedAt       sql.NullInt64                  `json:"resolvedAt"`
}

type File struct {
	ID         int64  `json:"id"`
	SourcePath string `json:"sourcePath"`
	TargetPath string `json:"targetPath"`
	Hash       string `json:"hash"`
	Size       int64  `json:"size"`
	ModTime    int64  `json:"modTime"`
	LastSynced int64  `json:"lastSynced"`
}

type IgnorePattern struct {
	ID        int64  `json:"id"`
	ProfileID int64  `json:"profileId"`
	Pattern   string `json:"pattern"`
	Type      string `json:"type"`
}

type Profile struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"createdAt"`
	UpdatedAt int64  `json:"updatedAt"`
}

type SyncRule struct {
	ID                int64            `json:"id"`
	ProfileID         int64            `json:"profileId"`
	SourceDir         string           `json:"sourceDir"`
	TargetDir         string           `json:"targetDir"`
	Status            types.SyncStatus `json:"status"`
	LastRunSuccessful sql.NullBool     `json:"lastRunSuccessful"`
	CreatedAt         int64            `json:"createdAt"`
	UpdatedAt         int64            `json:"updatedAt"`
}
