// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
)

type Conflict struct {
	ID               int64          `json:"id"`
	SourcePath       string         `json:"source_path"`
	TargetPath       string         `json:"target_path"`
	SourceHash       string         `json:"source_hash"`
	TargetHash       string         `json:"target_hash"`
	SourceTime       int64          `json:"source_time"`
	TargetTime       int64          `json:"target_time"`
	DetectedAt       int64          `json:"detected_at"`
	ResolutionStatus sql.NullString `json:"resolution_status"`
	ResolvedAt       sql.NullInt64  `json:"resolved_at"`
}

type File struct {
	ID         int64  `json:"id"`
	SourcePath string `json:"source_path"`
	TargetPath string `json:"target_path"`
	Hash       string `json:"hash"`
	Size       int64  `json:"size"`
	ModTime    int64  `json:"mod_time"`
	LastSynced int64  `json:"last_synced"`
}

type IgnorePattern struct {
	ID        int64  `json:"id"`
	ProfileID int64  `json:"profile_id"`
	Pattern   string `json:"pattern"`
	Type      string `json:"type"`
}

type Profile struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
}

type SyncRule struct {
	ID                int64         `json:"id"`
	ProfileID         int64         `json:"profile_id"`
	SourceDir         string        `json:"source_dir"`
	TargetDir         string        `json:"target_dir"`
	Enabled           bool          `json:"enabled"`
	LastRun           sql.NullInt64 `json:"last_run"`
	LastRunSuccessful sql.NullBool  `json:"last_run_successful"`
	CreatedAt         int64         `json:"created_at"`
	UpdatedAt         int64         `json:"updated_at"`
}
