// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"context"
)

type Querier interface {
	AddConflict(ctx context.Context, arg AddConflictParams) (int64, error)
	AddIgnorePattern(ctx context.Context, arg AddIgnorePatternParams) (int64, error)
	AddSyncRule(ctx context.Context, arg AddSyncRuleParams) (int64, error)
	CreateProfile(ctx context.Context, name string) (int64, error)
	DeleteFile(ctx context.Context, arg DeleteFileParams) error
	DeleteProfileByID(ctx context.Context, id int64) error
	DeleteProfileByName(ctx context.Context, name string) (int64, error)
	DeleteSyncRuleByProfileName(ctx context.Context, arg DeleteSyncRuleByProfileNameParams) (int64, error)
	GetConflict(ctx context.Context, id int64) (Conflict, error)
	GetFile(ctx context.Context, arg GetFileParams) (File, error)
	GetIgnorePattern(ctx context.Context, id int64) (IgnorePattern, error)
	GetProfile(ctx context.Context, id int64) (Profile, error)
	GetProfileIDByName(ctx context.Context, name string) (int64, error)
	GetProfileIDBySourceDir(ctx context.Context, sourceDir string) (int64, error)
	GetSyncRule(ctx context.Context, id int64) (SyncRule, error)
	GetSyncStatusByProfileName(ctx context.Context, name string) (GetSyncStatusByProfileNameRow, error)
	IsProfileExists(ctx context.Context, lower string) (int64, error)
	ListFiles(ctx context.Context, profileID int64) ([]File, error)
	ListIgnorePattern(ctx context.Context, profileID int64) ([]IgnorePattern, error)
	ListProfiles(ctx context.Context) ([]Profile, error)
	ListSyncRules(ctx context.Context, profileID int64) ([]SyncRule, error)
	ListSyncRulesGroupByProfile(ctx context.Context) ([]ListSyncRulesGroupByProfileRow, error)
	ListUnresolvedConflicts(ctx context.Context, profileID int64) ([]Conflict, error)
	RemoveIgnorePattern(ctx context.Context, id int64) error
	RemoveIgnorePatternByProfileName(ctx context.Context, arg RemoveIgnorePatternByProfileNameParams) (int64, error)
	ResolveConflict(ctx context.Context, arg ResolveConflictParams) error
	UpdateProfileByID(ctx context.Context, arg UpdateProfileByIDParams) error
	UpdateProfileByName(ctx context.Context, arg UpdateProfileByNameParams) (int64, error)
	UpdateSyncRule(ctx context.Context, arg UpdateSyncRuleParams) error
	UpsertFile(ctx context.Context, arg UpsertFileParams) error
}

var _ Querier = (*Queries)(nil)
