name: syncsnipe-frontend-test-suite
on:
  push:
    branches: [main]
    paths-ignore:
      - "**.go"
      - "**.sql"
      - "go.*"
      - "docs/**"
      - "**.md"
      - "**.txt"
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.go"
      - "**.sql"
      - "go.*"
      - "docs/**"
      - "**.md"
      - "**.txt"

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [22.11.x]
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install dependencies
      if: steps.file_types.outputs.watch_file_changes == 'true'
      run: pnpm install --frozen-lockfile
    - name: Run tests
      if: steps.file_types.outputs.watch_file_changes == 'true'
      run: pnpm test